import { getProductBySlug } from "@/providers/sanity/products";
import { Cartbutton, Productimage } from "@/lib/components";

export async function generateMetadata({ params }) {
  const { slug } = await params;
  const product = await getProductBySlug(slug);

  return {
    title: `${product.name} - Jack Hunt - Serious about sustainable skin care for men`,
    description: "Generated by create next app",
  };
}

export default async function Product({ params }) {
  const { slug } = await params;
  const product = await getProductBySlug(slug);

  return (
    <div className="bg-[#A3A2A4] min-h-screen pt-12">
      <div className="max-w-6xl mx-auto text-black">
        <div className="grid grid-cols-[3fr_2fr] gap-12">
          <div className="flex flex-col gap-8">
            <h1 className="text-5xl md:6-xl lg:text-7xl  font-bold underline underline-offset-5 decoration-[#E2EF70] max-w-prose break-inside-auto order-1 md:order-0">
              {product.name}
            </h1>
            <div className="w-full h-auto aspect-square relative bg-[#00000020]">
              <Productimage
                product={product}
                priority={true}
                size="600px"
                pad={150}
              />
            </div>
          </div>
          <div className="flex flex-col gap-6">
            <h2 className="text-2xl font-bold">
              The ultimate tanning game-changer, makes you beach-ready in a
              flash!
            </h2>
            <div>
              <h3 className="font-semibold mb-2">Why you'll want this:</h3>
              <ul className="space-y-2">
                <li className="flex items-start">
                  <span>✔️ Enriched with natural oils</span>
                </li>
                <li className="flex items-start">
                  <span>✔️ Fast-absorbing, non-sticky formula</span>
                </li>
                <li className="flex items-start">
                  <span>✔️ Environmentally conscious and cruelty-free</span>
                </li>
                <li className="flex items-start">
                  <span>✔️ Suitable for face and body</span>
                </li>
              </ul>
            </div>
            <div className="flex gap-6">
              <div>
                <div className="text-sm mb-1">Price</div>
                <div className="bg-yellow-200 inline-block px-2 py-1 font-bold">
                  €29.95
                </div>
              </div>
              <div>
                <div className="text-sm mb-1">Volume</div>
                <div className="inline-block py-1 font-bold">50ml</div>
              </div>
            </div>
            <Cartbutton product={product} variant="light" />
          </div>
        </div>
      </div>
    </div>
  );
}
