import { getProductBySlug } from "@/providers/sanity/products";

export const metadata = {
  title: "Jack Hunt - Serious about sustainable skin care for men",
  description: "Generated by create next app",
};

export default async function Product(props) {
  const { slug } = await props.params;
  const product = await getProductBySlug(slug);
  console.log(product);

  return (
    <>
      <div>This is a procduct for {product.price}</div>
    </>
  );
}
